version: '3.8'

services:
  ratio-bb-poc:
    build: .
    container_name: ratio-bb-poc
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ENV=PROD
      - LOG_LEVEL=DEBUG
      - MODE=live
      - CANDLE_PERIOD=5T
    ports:
      - "8080:8000"
    volumes:
      - type: tmpfs
        target: /app/logs
        tmpfs:
          size: 52428800
      - ./tmp:/app/tmp
    # Optioneel: data mount voor historische CSVs
    # - ./data:/app/data
    command: ["python", "-m", "src.run_once"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 400M