version: '3.8'

services:
  ratio-bb-poc:
    build: .
    container_name: ratio-bb-poc
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ENV=PROD
      - LOG_LEVEL=INFO
    volumes:
      - type: tmpfs
        target: /app/logs
        tmpfs:
          size: 52428800
    # Optioneel: data mount voor historische CSVs
    # - ./data:/app/data
    command: ["python", "main.py"]
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 400M