# KuCoin subaccount voor Ratio BB PoC

# 1) KuCoin API‐settings (loaded from environment)
kucoin_api_key: "${KUCOIN_API_KEY}"
kucoin_api_secret: "${KUCOIN_API_SECRET}"
kucoin_passphrase: "${KUCOIN_PASSPHRASE}"

# 2) Logging
log_level: WARNING
log_file: 'logs/app.log'

# 3) Filters & strategie‐parameters
nk_threshold: 0.0
volume_threshold: 0.0
short_ema_span: 9

# 4) Simulatie‐kosten
slippage_rate: 0.001
fee_rate: 0.001

# 5) Paden
data_path: 'data/historical.csv'

# 6) Realtime tickers
symbols:
  - THETA-USDT
  - TFUEL-USDT